image: docker:stable

variables:
  PRODUCTION_SERVER: 172.16.2.6
  DOCKER_REGISTRY: docker.autobiz.pro
  DOCKER_NAMESPACE: infra 
  PORT_MAPPING: 8080:8080
  DWH_PRIVATE_IP: 172.16.2.6
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_COMPOSE_FILE_GIT_RELATIVE_PATH: ./docker-compose-prod-deploy.yml
  SERVER_PROJECT_PATH_DOCKER_COMP_FILE: /home/gitlab/panel/docker-compose.yml
  SERVER_PROJECT_PATH: /home/gitlab/panel/

stages:
  - build
  - deploy

services:
  - docker:18.09-dind 

before_script:
  - source ./.cicd_tools/add_shared_cicd_tools.sh
  - source ./.cicd_tools_project_specific/add_panel_cicd_overrides_and_functions.sh
  - set_up_ssh_for_alpine
  - configure_access_to_bastion
  - set_up_access_to_docker_registry
  - make_sure_bash_is_installed

build:
  stage: build
  image: docker/compose:1.25.0-rc1-alpine
  script: 
    # I use the following script because sh cannot do bash's for-loops.
    - bash ./.cicd_tools_project_specific/build_and_push_dqc_panel_docker_images.sh ${DOCKER_REGISTRY} ${DOCKER_NAMESPACE} ${CI_COMMIT_SHA:0:8}
  tags:
    - docker

deploy:
  stage: deploy
  script: 
    - set_deploy_server ${PRODUCTION_SERVER} 
    - remove_the_previous_stack_if_it_exists_and_create_new_deployment_folder
    - change_docker_compose_for_deployment_server_and_send_new_docker_compose_file
    - set_up_access_to_docker_registry_in_server
    - create_network_to_make_dwh_accessible
    - execute_docker_compose_up
  tags:
    - docker
  when: manual
