version: '3.7'
services:

  nifi:
    image: DOCKER_REGISTRY/DOCKER_NAMESPACE/panel2_nifi:CI_COMMIT_SHA
    restart: unless-stopped
    ports:
      - 18080:8080
    volumes:
      - nifi_logs:/opt/nifi/nifi-current/logs
      - nifi_db:/usr/local/data/db
    networks:
      - panel_elk
    extra_hosts:
       - "dwh:DWH_PRIVATE_IP"
 
  elasticsearch:
   image: DOCKER_REGISTRY/DOCKER_NAMESPACE/panel2_elasticsearch:CI_COMMIT_SHA
   restart: unless-stopped
   volumes:
     - type: volume
       source: elasticsearch
       target: /usr/share/elasticsearch/data
   ports:
     - "9200:9200"
     - "9300:9300"
   environment:
     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
     ELASTIC_PASSWORD: "dqc_panel_pass"
   networks:
     - panel_elk
 
  logstash:
   image: DOCKER_REGISTRY/DOCKER_NAMESPACE/panel2_logstash:CI_COMMIT_SHA
   restart: unless-stopped
   ports:
     - "5044:5044"
     - "9600:9600"
   environment:
     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
   networks:
     - panel_elk
   depends_on:
     - elasticsearch
 
  kibana:
   image: DOCKER_REGISTRY/DOCKER_NAMESPACE/panel2_kibana:CI_COMMIT_SHA
   restart: unless-stopped
   ports:
     - "5601:5601"
   networks:
     - panel_elk
   depends_on:
     - elasticsearch

  filebeat:
   image: DOCKER_REGISTRY/DOCKER_NAMESPACE/panel2_filebeat:CI_COMMIT_SHA
   restart: unless-stopped
   networks:
     - panel_elk
   volumes:
     - type: volume
       source: nifi_logs
       target: /usr/share/filebeat/logs
       read_only: true
     - filebeat:/usr/share/filebeat/data
   depends_on:
     - logstash

  grafana:
   image: DOCKER_REGISTRY/DOCKER_NAMESPACE/panel2_grafana:CI_COMMIT_SHA
   restart: unless-stopped
   ports:
     - "3000:3000"
   networks:
     - panel_elk

networks:
  panel_elk:
    external: true
    name: panel_elk

volumes:
  elasticsearch:
  nifi_logs:
  nifi_db:
  filebeat:
    driver: local
