
[[servers]]
host = "exch2k16.autobiz.com"

port = 636
use_ssl = true
start_tls = false
ssl_skip_verify = true
bind_dn = "CptSvc_grafana"
bind_password = 'sdz85KK8erhb488/zafvAZAeZ6'
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["DC=autobiz,DC=local"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email =  "mail"
