FROM docker.autobiz.pro/infra/nifi_autobiz:latest

COPY nifi/requirements.txt /tmp
USER root
RUN  pip3 install --upgrade numpy==1.16.2 &&  pip3 install --upgrade pip -r /tmp/requirements.txt

RUN mkdir -p /usr/local/data/input && \
    mkdir -p /usr/local/data/backup && \
    chmod -R 777 /usr/local/data && \
    mkdir -p /usr/local/src

USER nifi
EXPOSE 8080
