FROM docker.autobiz.pro/infra/nifi_autobiz:latest

USER root
COPY ./requirements.txt /tmp

RUN  pip3 install -r /tmp/requirements.txt

RUN mkdir -p /usr/local/data/input && \
    mkdir -p /usr/local/data/backup && \
    chmod -R 777 /usr/local/data && \
    mkdir -p /usr/local/src && \
    mkdir -p /usr/local/bin/src

USER nifi
