filebeat.inputs:

- type: log
  paths:
   - '/usr/share/filebeat/logs/dqc_panel*.log'
  fields_under_root: true
  fields:
   attrs:
    autobiz.app: dqc_panel
    autobiz.role: report
    autobiz.env: dev

output.logstash:
 hosts: ['logstash:5044']
 timeout: 30s
