version: '2.0'
services:


  nifi_panel_patrick:
    container_name: nifi_panel_fabien
    build:
      context: .
      dockerfile: ./nifi/Dockerfile
    #tty: true
    ports:
      - 48080:8080
    volumes:
      - ./../logs/nifi:/nifi/logs
      - ./../data/input:/data/input
      - ./../data/sqlite:/db
      - ./../data/backup:/data/backup
      - ./nifi/conf:/nifi/conf
      - ./../application:/usr/local/src

